#cloud-config
packages:
- git

runcmd:
- echo 'iniciando back' > /var/log/back.log
# - sudo snap install node --classic
- 'curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash'
- 'apt-get install nodejs -y'
- git clone https://github.com/italovisconti/NNotes-RestAPI.git /opt/app/myapp
- cd /opt/app/myapp && npm install
- echo 'node y repositorio listo' >> /var/log/back.log